### PR TITLE
Attempt at migration to latest sveltekit version

### PR DESCRIPTION
**Pull request by myway880**
Hi, I have updated to latest version, I don't expect you to accept this, I'm mostly interested in a simple critic ??

### CODE REVIEW

**Comment by myway880** [comment]
Sorry, the RSS feed is broken, and I don't know how to fix it yet.

**Comment by matfantinel** [comment]
Wow, I wasn't expecting this - thank you!

This is definitely something I've been wanting to do but haven't found the time to do yet. Though I'd still like to do it myself for the sake of understanding the changes better (and updating my blog post about SvelteKit), I'll definitely check what you've done and compare with my changes as I make them. I can add whatever feedback I have as comments here if you'd like.

As for the RSS, I never really liked my implementation - and perhaps a better way to do it has surfaced after I initially wrote this one. So maybe it being broken is the perfect excuse to look more into it.

**Comment by myway880** [comment]
Thanks, any comment would be helpful ...

**Comment by myway880** [comment]
Sorry to bother you, just in case you know of the top of your head...
The RSS endpoint is supposed to return a response object, but this mean that it store the RSS XML in JSON file as a double-quoted string, but a double-quoted XML are not valid XML, so the browser cannot display it…  I don's know if this is a bug in Sveltekit or if I'm too noob to figure it out??
Do you have any suggestion, feel free to ignore this, I just wanted to file a bug report if it was a bug..

**Comment by matfantinel** [comment]
@myway880 this is great! I had a bit of time to dig into it and understand all the changes. I only had to create a `+layout.js` file in the `routes` folder with `export const prerender = true;` inside of it so `npm run build` would work to build an entirely static site.

I followed the official migration guide and ended up with a pretty similar result to yours. So I'm going to merge your Pull Request instead so that you're credited for the contribution!

I'm just gonna merge it into a separate branch and not on main right now because there's still some work I wanna do before I push it - mainly running `npm run format` to enforce the code style and update the SvelteKit blog post to reflect the new files structure.

Thanks again for taking the time to do this! I really appreciate it!

**Comment by myway880** [comment]
That is great, thank you for that, although I have to admit I'm a little disappointed, lol …
I was hoping for more of :
-You did this and this wrong, 
-It should be like that. 
feedback just to learn from you :)...

**Comment by matfantinel** [comment]
@myway880 hah, well you did a good job and that makes it harder to do any criticism 😅

I guess the two things I've noticed are that the code wasn't fully compiling for prod (npm run build) since the prerender setting was in the wrong file. Worked on dev because it doesn't try to fully compile into a static site when running locally.

Also, some code formatting differences (like spacing when declaring variables) which were very minor and could be quickly fixed with npm run format (I use Prettier when developing which makes that easy to do as well!)

Perhaps if I find out I need to change something before I deploy the changes I'll let you know :)

**Pull request merged**
